[betterDungeons.general]
enableHeads = true
removeVanillaDungeons = true
enableNetherBlocks = true
[betterDungeons.zombieDungeon]
zombieDungeonMaxSurfaceStaircaseLength = 20
[betterDungeons.smallDungeon]
bannerMaxCount = 2
chestMinCount = 2
chestMaxCount = 4
enableOreProps = true
[betterDungeons.smallNetherDungeon]
enabled = true
witherSkeletonsDropWitherSkulls = true
blazesDropBlazeRods = true
bannerMaxCount = 2
