# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				axolotl = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				bat = true
				frog = true
				hoglin = true
				experience_bottle = true
				rabbit = true
				silverfish = true
				firework_rocket = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wither_skeleton = true
				vex = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				ender_dragon = true
				evoker = true
				mooshroom = true
				glow_squid = true
				warden = true
				glow_item_frame = false
				squid = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				ravager = true
				donkey = true
				evoker_fangs = true
				fox = true
				tropical_fish = true
				chest_minecart = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				ender_pearl = true
				guardian = true
				ghast = true
				sheep = true
				fireball = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				wither_skull = true
				eye_of_ender = true
				wolf = true
				villager = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				boat = true
				strider = true
				polar_bear = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true
				wither = true

			[light_sources.settings.entities.the_bumblezone]
				honey_slime = true
				beehemoth = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				beach_creeper = true
				cave_creeper = true
				savannah_creeper = true
				hills_creeper = true
				spruce_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				dark_oak_creeper = true
				dripstone_creeper = true
				mushroom_creeper = true

			[light_sources.settings.entities.takesapillage]
				legioner = true
				archer = true
				skirmisher = true
				clay_golem = true

			[light_sources.settings.entities.progressivebosses]
				larva = true
				wither_minion = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				blue_fireball = true
				lich = true
				comet = true
				soul_star = true

